// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import GameFormController from "./game_form_controller"
application.register("game-form", GameFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PlaygroundController from "./playground_controller"
application.register("playground", PlaygroundController)

import ResultsBlueController from "./results_blue_controller"
application.register("results-blue", ResultsBlueController)

import ResultsRedController from "./results_red_controller"
application.register("results-red", ResultsRedController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import UpcomingGamesController from "./upcoming_games_controller"
application.register("upcoming-games", UpcomingGamesController)
